# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-04 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fiction',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('words', models.IntegerField()),
                ('wordfre', models.TextField()),
                ('sl', models.FloatField()),
                ('wl', models.FloatField()),
                ('RE', models.FloatField()),
                ('TFIDF', models.TextField()),
                ('reArticle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('readinglist', models.TextField()),
                ('score', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieClass',
            fields=[
                ('movieId', models.TextField(primary_key=True, serialize=False)),
                ('movie_info', models.TextField(max_length=1000)),
                ('movie_src', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('essay', models.TextField(default='null')),
            ],
        ),
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('userId', models.TextField(primary_key=True, serialize=False)),
                ('user_Recommand', models.TextField()),
                ('user_History', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('words', models.TextField()),
            ],
        ),
    ]
