# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='essay',
            field=models.TextField(default='DEFAULT VALUE'),
        ),
    ]
