# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_user_essay'),
    ]

    operations = [
        migrations.CreateModel(
            name='fiction',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('words', models.IntegerField()),
                ('wordfre', models.TextField()),
                ('sl', models.FloatField()),
                ('wl', models.FloatField()),
                ('RE', models.FloatField()),
                ('TFIDF', models.TextField()),
                ('reArticle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('readinglist', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='essay',
            field=models.TextField(default='null'),
        ),
    ]
